version: '3.8'

services:
  feedllama:
    image: ghcr.io/astrabert/bluesky-feedllama:main
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia